[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "partitioning"
version = "0.1.0"
description = "A project for partitioning"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
dependencies = [
    # List your project dependencies here
]

[tool.setuptools.packages.find]
where = ["src"]
