name: CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  schedule:
    # At 17:31 every Tuesday (UTC)
    # At 9:31 every Tuesday (PST)
    - cron: "0 12 1 * 1"  # Every first Monday of the month at 12:00 UTC
  workflow_dispatch:

jobs:
  # Run tests
  test:
    runs-on: ubuntu-latest  # Adjusted to ubuntu-latest for simplicity

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Test with pytest
        run: |
          python -m pytest tests/  # Use `python -m pytest` to ensure pytest from correct environment
